"""Seed list of company Greenhouse boards (public board tokens).

Every token here was verified live to return jobs. Over-inclusion is
still safe: the transport skips any board that later 404s or errors, so
a stale token just drops out silently. Pass your own tuple to
``GreenhouseProvider`` / ``HttpxGreenhouseTransport`` to narrow or extend.
"""

from __future__ import annotations

DEFAULT_COMPANY_BOARDS: tuple[str, ...] = (
    "affirm",
    "airbnb",
    "airtable",
    "asana",
    "betterment",
    "bitpanda",
    "blend",
    "brave",
    "brex",
    "calendly",
    "cameo",
    "carta",
    "checkr",
    "chime",
    "cloudflare",
    "coinbase",
    "collectivehealth",
    "coreweave",
    "databricks",
    "datadog",
    "discord",
    "dropbox",
    "duolingo",
    "elastic",
    "faire",
    "figma",
    "fivetran",
    "flexport",
    "gemini",
    "gitlab",
    "gusto",
    "instabase",
    "instacart",
    "intercom",
    "klaviyo",
    "lattice",
    "launchdarkly",
    "life360",
    "lyft",
    "marqeta",
    "mercury",
    "mixpanel",
    "mongodb",
    "monzo",
    "netlify",
    "nextdoor",
    "okta",
    "peloton",
    "pendo",
    "pinterest",
    "postman",
    "reddit",
    "ripple",
    "robinhood",
    "roblox",
    "rockstargames",
    "samsara",
    "scaleai",
    "sigmacomputing",
    "sofi",
    "stripe",
    "twilio",
    "twitch",
    "udemy",
    "upstart",
    "vercel",
    "webflow",
    "wise",
    "zocdoc",
    "zoominfo",
)
